### ISSUE TITLE
DoctrineORMInfo class unnecessary check?

### ISSUE THREAD

**Issue by ceesvanegmond** [a2lix/AutoFormBundle#15]
Hi there,

I'm using `TranslationFormBundle` and its working perfectly. In my case; i'm using the `TranslationsType` in Sonata to add translated field. I want to use a ManyToOne field as translated field; and I do get an error. The error is `class xxx doesn't have a field yyy`. Where yyy is the ManyToOne field.

After a bit of researching I found a solution. If I remove the following check (https://github.com/a2lix/AutoFormBundle/blob/master/src/ObjectInfo/DoctrineORMInfo.php#L65) everything is working fine.

My question is; can this check be removed? Or why is it there?

**Comment by ceesvanegmond** [comment]
Nobody?

**Comment by tamert** [comment]
I'm using EasyAdmin, and I had the same problem ... did you  fixed the issue ?

**Comment by muhep06** [comment]
up

**Comment by bilalceyylan** [comment]
Up!

**Comment by tamererdogan** [comment]
I have a same issue, please solve this problem. Thank you !

**Comment by cagrisungur** [comment]
any news?

**Comment by tamert** [comment]
Unfortunately, I manipulated DoctrineORMInfo file

```yaml
  a2lix_auto_form.object_info.doctrine_orm_info:
    class: App\ORM\DoctrineORMInfo
    arguments: ['@a2lix_auto_form.doctrine.metadata_factory']
```
